# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 495fab2be98013de829e4a775a948e80139e65fc1d5eae7bb686d7b60ba5ebc5236b112df91eb8ae46390f0d33740dce88603b8f319241f0fdff895d1536e709

test:
  secret_key_base: f71c543e44a6e9571ba883b2a4adf49da8ee62fdc827e0689ab72a6255a1227f4ac40f67d2adb6487b82aee798e2f30937bf5e571b3354c02f394c6e30eb7112

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
